root = "."
tmp_dir = "tmp"
testdata_dir = "testdata"
build_dir = "build"

[build]
    bin = "tmp/main"
    cmd = "go build -o {{.Output}} {{.Input}}"
    exclude = ["tmp/*", "client/*", "client/node_modules/*"]
    log = "build.log"
    include = ["**/*.go"]
    ignore = ["tmp/*", "client/*", "client/node_modules/*"]
